export const DashboardPermissionKeys = {
    VIEW_DASHBOARD: 'VIEW_DASHBOARD',

    VIEW_EMPLOYEE_DASHBOARD: 'VIEW_EMPLOYEE_DASHBOARD',
    VIEW_MY_REQUISITION_STATS: 'VIEW_MY_REQUISITION_STATS',
    VIEW_MY_ASSIGNED_ITEMS: 'VIEW_MY_ASSIGNED_ITEMS',

    VIEW_MANAGER_DASHBOARD: 'VIEW_MANAGER_DASHBOARD',
    VIEW_DEPARTMENT_REQUISITION_STATS: 'VIEW_DEPARTMENT_REQUISITION_STATS',
    VIEW_PENDING_APPROVAL_STATS: 'VIEW_PENDING_APPROVAL_STATS',
    VIEW_DEPARTMENT_INVENTORY_STATS: 'VIEW_DEPARTMENT_INVENTORY_STATS',

    VIEW_PROCUREMENT_DASHBOARD: 'VIEW_PROCUREMENT_DASHBOARD',
    VIEW_PROCUREMENT_QUEUE_STATS: 'VIEW_PROCUREMENT_QUEUE_STATS',
    VIEW_RFQ_STATS: 'VIEW_RFQ_STATS',
    VIEW_QUOTATION_STATS: 'VIEW_QUOTATION_STATS',
    VIEW_PURCHASE_ORDER_STATS: 'VIEW_PURCHASE_ORDER_STATS',
    VIEW_RECENT_PURCHASE_ORDERS: 'VIEW_RECENT_PURCHASE_ORDERS',
    VIEW_TODAY_DELIVERIES: 'VIEW_TODAY_DELIVERIES',

    VIEW_INVENTORY_DASHBOARD: 'VIEW_INVENTORY_DASHBOARD',
    VIEW_STOCK_STATS: 'VIEW_STOCK_STATS',
    VIEW_LOW_STOCK_ALERTS: 'VIEW_LOW_STOCK_ALERTS',
    VIEW_INVENTORY_ASSIGNMENT_STATS: 'VIEW_INVENTORY_ASSIGNMENT_STATS',
    VIEW_RECEIVING_STATS: 'VIEW_RECEIVING_STATS',

    VIEW_FINANCE_DASHBOARD: 'VIEW_FINANCE_DASHBOARD',
    VIEW_PURCHASE_COST_STATS: 'VIEW_PURCHASE_COST_STATS',
    VIEW_BUDGET_STATS: 'VIEW_BUDGET_STATS',

    VIEW_EXECUTIVE_DASHBOARD: 'VIEW_EXECUTIVE_DASHBOARD',
    VIEW_EXECUTIVE_PROCUREMENT_STATS: 'VIEW_EXECUTIVE_PROCUREMENT_STATS',
    VIEW_DASHBOARD_CHARTS: 'VIEW_DASHBOARD_CHARTS',
    VIEW_DASHBOARD_ALERTS: 'VIEW_DASHBOARD_ALERTS',

    VIEW_ADMIN_DASHBOARD: 'VIEW_ADMIN_DASHBOARD',
    VIEW_SYSTEM_STATS: 'VIEW_SYSTEM_STATS',

    VIEW_DASHBOARD_REPORTS: 'VIEW_DASHBOARD_REPORTS',
    EXPORT_DASHBOARD_REPORTS: 'EXPORT_DASHBOARD_REPORTS',
    VIEW_DASHBOARD_QUICK_ACTIONS: 'VIEW_DASHBOARD_QUICK_ACTIONS'
} as const;